

export const actionsTypes = { 
    REQUEST_DATA:"REQUEST_DATA",
    ERROR_DATA:"ERROR_DATA",
    SET_WINNERS: "SET_WINNERS",
    SET_SETTINGS: "SET_SETTINGS",
    SET_USER:"SET_USER",
    SET_MODE:"SET_MODE",
    SET_DELAY:"SET_DELAY",
    SET_FIELD_SIZE:"SET_FIELD_SIZE",
    SET_FIELD_ARRAY:"SET_FIELD_ARRAY",
    START_GAME:"START_GAME",
    FINISH_GAME:"FINISH_GAME",
    SET_GAME_PERMISSION:"SET_GAME_PERMISSION",
    CLICK_SQUARE:"CLICK_SQUARE",
    SET_SQUARE_BLUE:"SET_SQUARE_BLUE",
    SET_SQUARE_RED:"SET_SQUARE_RED",
}