

export const actionsTypes = {
    SET_WINNERS: "SET_WINNERS", 
    SET_SETTINGS: "SET_SETTINGS",
    SET_USERNAME:"SER_USERNAME",
    SET_DELAY:"SET_DELAY",
    SET_FIELD_SIZE:"SET_FIELD_SIZE",
    SET_FIELD_ARRAY:"SET_FIELD_ARRAY",
    START_GAME:"START_GAME"
}